### ISSUE TITLE
GAT Test Runner - #14 - moneymoney

### ISSUE THREAD

**Issue by leukanos** [dbaspi9/psc#3]
# #14 - moneymoney

[View result in Test Runner portal](https://test-runner-qa.gatserver.com/applications/1/results/14)

| _ | _ |
| --- | --- |
| outcome | Failed |
| total steps | 7 |
| browsers | Windows Chrome |
| started | April 03, 2017 07:29 |
| environment | staging |

| action | question | Windows Chrome |
| --- | --- | --- |
| In the browser, enter {{environment.url}} and press Enter. | Was the Moneylion prequalify page loaded successfully? | Failed |
| Fill in ALL fields in the application form. Use the following data for specific fields: How Much Do You Need?: 5000 | You'll use your loan for...: select any | Email Address: {{random.first_name}}{{random.number}}@moneylion.com | First Name: 800-800 |Last Name: 100-200-300-400-500-400000-17.0-4.3-4-1 | Mobile Phone Number: 6505323283 | Date of Birth: 08/09/1977 | Home Address line1: ml-successlion-A_prime-A_prime | line2: anytext | City : 60 | State: Illinois (IL) | ZIP Code: 12345 | Can the data be filled in? | Failed |
| Use random digits for Social security number(do not use patterns like 123456789 or 999999999) | Click on Step 2 | Is the next page loaded? | Failed |
| Fill in ALL fields in the application form. Use the following data for specific fields: Job status: select Employed | Gross Monthly Income: 150000 | Do you rent or own: select any | Your monthly payment: 3000 | Create a password: test1234 | I have read the disclosure...: tick the checkbox | Yes, enroll me in FREE credit monitoring...: untick the checkbox  | Can the data be filled in? | Failed |
| Complete the "I'm Not a robot" test and click on the Check your rate button | Is the "Let's confirm your identity" page loaded? | Failed |
| Click on the "SKIP >>" button on the social login page | Is the "Congratulations! You're Prequalified" page loaded? | Failed |
| Adjust the loan amount slider to a value and click on the "GET FUNDED" button | Is the "Let's Connect Your Bank Account" page loaded? | Failed |

### Windows Chrome details

|   | Tester 1 |
| --- | --- |
| In the browser, enter {{environment.url}} and press Enter.<br />Was the Moneylion prequalify page loaded successfully?<br />outcome: Failed | Response: no<br />Problem: test<br />![thumb](http://gat-system-qa.s3.amazonaws.com/images/test_case_step_responses/screenshots/000/004/084/thumb/24059ab743368b2d320a45a3e9a99a00a01783bf1a516315.png?1491204674)<br />[enlarge](http://gat-system-qa.s3.amazonaws.com/images/test_case_step_responses/screenshots/000/004/084/original/24059ab743368b2d320a45a3e9a99a00a01783bf1a516315.png?1491204674) |
| Fill in ALL fields in the application form. Use the following data for specific fields: How Much Do You Need?: 5000 | You'll use your loan for...: select any | Email Address: {{random.first_name}}{{random.number}}@moneylion.com | First Name: 800-800 |Last Name: 100-200-300-400-500-400000-17.0-4.3-4-1 | Mobile Phone Number: 6505323283 | Date of Birth: 08/09/1977 | Home Address line1: ml-successlion-A_prime-A_prime | line2: anytext | City : 60 | State: Illinois (IL) | ZIP Code: 12345<br />Can the data be filled in?<br />outcome: n/d | n/d |
| Use random digits for Social security number(do not use patterns like 123456789 or 999999999) | Click on Step 2<br />Is the next page loaded?<br />outcome: n/d | n/d |
| Fill in ALL fields in the application form. Use the following data for specific fields: Job status: select Employed | Gross Monthly Income: 150000 | Do you rent or own: select any | Your monthly payment: 3000 | Create a password: test1234 | I have read the disclosure...: tick the checkbox | Yes, enroll me in FREE credit monitoring...: untick the checkbox <br />Can the data be filled in?<br />outcome: n/d | n/d |
| Complete the "I'm Not a robot" test and click on the Check your rate button<br />Is the "Let's confirm your identity" page loaded?<br />outcome: n/d | n/d |
| Click on the "SKIP >>" button on the social login page<br />Is the "Congratulations! You're Prequalified" page loaded?<br />outcome: n/d | n/d |
| Adjust the loan amount slider to a value and click on the "GET FUNDED" button<br />Is the "Let's Connect Your Bank Account" page loaded?<br />outcome: n/d | n/d |

**Comment by leukanos** [comment]
sorry, I was checking something 😈

**Comment by dbaspi9** [comment]
no problem ;)
